#!/bin/bash

echo "<div class=\"form-check\">"
echo "  <input class=\"form-check-input\" type=\"radio\" name=\"$1\" id=\"$1Radios1\" value=\"option1\" checked>"
echo "  <label class=\"form-check-label\" for=\"$1Radios1\">"
echo "    Default radio"
echo "   </label>"
echo "</div>"
echo "<div class=\"form-check\">"
echo "  <input class=\"form-check-input\" type=\"radio\" name=\"$1\" id=\"$1Radios2\" value=\"option2\">"
echo "  <label class=\"form-check-label\" for=\"$1Radios2\">"
echo "    Second default radio"
echo "  </label>"
echo "</div>"
echo "<div class=\"form-check disabled\">"
echo "  <input class=\"form-check-input\" type=\"radio\" name=\"$1\" id=\"$1Radios3\" value=\"option3\" disabled>"
echo "  <label class=\"form-check-label\" for=\"$1Radios3\">"
echo "    Disabled radio"
echo "  </label>"
echo "</div>"